services:
  # Database Service (MySQL)
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_ROOT_PASSWORD: creator
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"  # Default MySQL port
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
 
  # Backend Service
  backend:
    build:
      context: "D:/bravo/Backend"
    container_name: backend
    ports:
      - "5000:5000"  # Port for backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: creator
      DB_NAME: auth_db
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: always
 
  # Frontend Service
  frontend:
    build:
      context: "D:/bravo/my-app"
    container_name: frontend
    ports:
      - "3000:3000"  # Port for frontend
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
 
networks:
  app-network:
 
volumes:
  db_data: