apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: divoniwesly/mantapbro:backend_1.1.9 # Ganti dengan image backend Anda
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: initesting123
        - name: DB_NAME
          value: auth_db
        - name: DB_PORT
          value: "3306"
        - name: BACKEND_API
          value: "http://localhost:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort  # Mengubah tipe menjadi NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005  # Anda dapat menentukan port NodePort secara manual, atau biarkan kosong untuk memilih secara otomatis
  selector:
    app: backend
