name: Build and Push Docker Images to DockerHub

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pitherli/bravotravel01:piter
    - name: Push image to DockerHub
      run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_ACCESS_TOKEN }}"
          docker push pitherli/bravotravel01:piter

