name: Build and Push Docker Images to DockerHub

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pitherli/bravotravel01:piter
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u pitherli --password-stdin
    - name: Push Docker Image
      run: docker push pitherli/bravotravel01:piter
